import { expect, test } from '@playwright/test'
import { createConfirmedAccount, signIn } from './fixtures/localSupabase'
import { enterQuickAmount, openCreateSpace, openQuickSplit } from './fixtures/quickAdd'

test('keeps capture history and split cancellation separate without losing the draft', async ({ page }, testInfo) => {
  const runId = `${Date.now().toString(36)}-${testInfo.parallelIndex}`
  const account = await createConfirmedAccount('universal-history', 'History Tester', runId)
  await signIn(page, account)
  await page.goto('/spaces')
  await openCreateSpace(page)
  await page.getByLabel('Name').fill('History Trip')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'History Trip' })).toBeVisible()
  const spaceUrl = page.url()

  await page.goto('/friends')
  await page.getByRole('button', { name: 'Quick add expense' }).click()
  const capture = page.getByRole('dialog', { name: 'Quick Add', exact: true })
  await expect(capture.getByRole('button', { name: /^Split/ })).toContainText('Personal')
  await page.goBack()
  await expect(page).toHaveURL(/\/friends$/)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goForward()
  await expect(capture).toBeVisible()
  await capture.getByRole('button', { name: 'Close Quick Add' }).click()

  await page.goto(spaceUrl)
  await page.getByRole('button', { name: '+ Add expense' }).click()
  await enterQuickAmount(capture, '120')
  await capture.getByRole('button', { name: 'Food', exact: true }).click()
  await capture.getByRole('textbox', { name: 'Description' }).fill('Dinner')
  let split = await openQuickSplit(capture, page)
  await expect(split.getByText('History Trip', { exact: true })).toBeVisible()
  await split.getByRole('button', { name: 'Amounts', exact: true }).click()
  await split.getByRole('textbox', { name: 'Share for History Tester' }).fill('120')
  // Cancel discards panel edits, while keeping the surrounding capture draft.
  await split.getByRole('button', { name: 'Close panel' }).click()
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('120')
  await expect(capture.getByRole('textbox', { name: 'Description' })).toHaveValue('Dinner')
  split = await openQuickSplit(capture, page)
  await expect(split.getByRole('button', { name: 'Equally', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await split.getByRole('button', { name: 'Remove split · personal expense' }).click()
  await expect(split).toHaveCount(0)
  await expect(capture.getByRole('button', { name: /^Split/ })).toContainText('Personal')
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('120')
  await expect(capture.getByRole('textbox', { name: 'Description' })).toHaveValue('Dinner')
  await expect(capture.getByRole('button', { name: 'Food', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.goBack()
  await expect(page).toHaveURL(spaceUrl)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.goForward()
  await expect(capture.getByRole('button', { name: /^Split/ })).toContainText('Personal')
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('120')
})

test('does not expose an unsaved session after the authenticated identity changes', async ({ page }, testInfo) => {
  const runId = `${Date.now().toString(36)}-${testInfo.parallelIndex}`
  const [accountA, accountB] = await Promise.all([
    createConfirmedAccount('identity-a', 'Identity A', runId),
    createConfirmedAccount('identity-b', 'Identity B', runId),
  ])
  await signIn(page, accountA)
  await page.getByRole('button', { name: 'Quick add expense' }).click()
  const capture = page.getByRole('dialog', { name: 'Quick Add', exact: true })
  await enterQuickAmount(capture, '88')
  await capture.getByRole('textbox', { name: 'Description' }).fill('User A secret')
  await capture.getByRole('button', { name: 'Close Quick Add' }).click()
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Me', exact: true }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await signIn(page, accountB)
  await page.getByRole('button', { name: 'Quick add expense' }).click()
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('')
  await expect(capture.getByRole('textbox', { name: 'Description' })).toHaveValue('')
  await expect(capture.getByText('User A secret')).toHaveCount(0)
  await capture.getByRole('button', { name: 'Close Quick Add' }).click()
  await page.getByRole('navigation', { name: 'Primary navigation' }).getByRole('button', { name: 'Me', exact: true }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await signIn(page, accountA)
  await page.getByRole('button', { name: 'Quick add expense' }).click()
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('88')
  await expect(capture.getByRole('textbox', { name: 'Description' })).toHaveValue('User A secret')
})

test('preserves an explicit category and currency while adding and removing a split', async ({ page }, testInfo) => {
  const runId = `${Date.now().toString(36)}-${testInfo.parallelIndex}`
  const account = await createConfirmedAccount('category-provenance', 'Category Tester', runId)
  await signIn(page, account)
  await page.goto('/spaces')
  await openCreateSpace(page)
  await page.getByLabel('Name').fill('Category Trip')
  await page.getByRole('button', { name: 'Create', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Category Trip' })).toBeVisible()
  await page.getByRole('button', { name: '+ Add expense' }).click()
  const capture = page.getByRole('dialog', { name: 'Quick Add', exact: true })
  await enterQuickAmount(capture, '9.99')
  await capture.getByRole('button', { name: 'Shopping', exact: true }).click()
  await capture.getByRole('textbox', { name: 'Description' }).fill('Dinner description with a user-selected category')
  await capture.getByLabel('Currency', { exact: true }).selectOption('USD')
  let split = await openQuickSplit(capture, page)
  await split.getByRole('button', { name: 'Remove split · personal expense' }).click()
  await expect(capture.getByRole('button', { name: 'Shopping', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(capture.getByLabel('Currency', { exact: true })).toHaveValue('USD')
  await expect(capture.getByRole('textbox', { name: 'Amount' })).toHaveValue('9.99')
  split = await openQuickSplit(capture, page)
  await split.getByRole('button', { name: 'Trips', exact: true }).click()
  await split.getByRole('button', { name: /^Category Trip(?: ›)?$/ }).click()
  await split.getByRole('button', { name: 'Apply split', exact: true }).click()
  await expect(capture.getByRole('button', { name: 'Shopping', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(capture.getByLabel('Currency', { exact: true })).toHaveValue('USD')
  await expect(capture.getByRole('textbox', { name: 'Description' })).toHaveValue('Dinner description with a user-selected category')
})
